CREATE TABLE interview_question (
  question_id VARCHAR(64) PRIMARY KEY,
  title VARCHAR(512) NOT NULL,
  category VARCHAR(128),
  difficulty VARCHAR(32),
  question_type VARCHAR(32),
  content TEXT NOT NULL,
  answer TEXT,
  tags_json TEXT,
  enabled BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  bank_type VARCHAR(32) NOT NULL DEFAULT 'qa',
  coding_meta_json TEXT,
  tenant_id VARCHAR(64) NOT NULL DEFAULT 'default-tenant'
);

CREATE TABLE interview_exam (
  exam_id VARCHAR(64) PRIMARY KEY,
  title VARCHAR(512),
  status VARCHAR(32),
  total_count INTEGER,
  answered_count INTEGER,
  score NUMERIC(8,2),
  started_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  submitted_at TIMESTAMPTZ,
  duration_minutes INTEGER DEFAULT 30,
  strategy_json TEXT,
  expires_at TIMESTAMPTZ,
  tenant_id VARCHAR(64) NOT NULL,
  user_id VARCHAR(64) NOT NULL
);

CREATE TABLE interview_exam_question (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  exam_id VARCHAR(64) NOT NULL,
  question_id VARCHAR(64) NOT NULL,
  display_order INTEGER,
  user_answer TEXT,
  correct BOOLEAN,
  score NUMERIC(8,2),
  evaluated_at TIMESTAMPTZ,
  CONSTRAINT fk_interview_exam_question_exam FOREIGN KEY (exam_id) REFERENCES interview_exam(exam_id) ON DELETE CASCADE,
  CONSTRAINT fk_interview_exam_question_question FOREIGN KEY (question_id) REFERENCES interview_question(question_id) ON DELETE CASCADE
);

CREATE INDEX idx_interview_question_bank_type ON interview_question (bank_type, category, difficulty, question_type);
CREATE INDEX idx_interview_question_tenant_updated ON interview_question (tenant_id, updated_at DESC);
CREATE INDEX idx_interview_question_category ON interview_question (category, difficulty);
CREATE INDEX idx_interview_question_updated ON interview_question (updated_at DESC);
CREATE INDEX idx_interview_exam_owner_started ON interview_exam (tenant_id, user_id, started_at DESC);
CREATE INDEX idx_interview_exam_started ON interview_exam (started_at DESC);
CREATE INDEX idx_interview_exam_question_exam ON interview_exam_question (exam_id, display_order);
