CREATE TABLE agent_run_checkpoint (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  session_id VARCHAR(128) NOT NULL,
  run_id VARCHAR(128) NOT NULL,
  stage VARCHAR(128) NOT NULL,
  sequence BIGINT NOT NULL,
  payload_json JSONB NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE chat_message_log (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  session_id VARCHAR(128) NOT NULL,
  role VARCHAR(32) NOT NULL,
  content TEXT,
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  metadata_json TEXT,
  tenant_id VARCHAR(64) NOT NULL,
  user_id VARCHAR(64) NOT NULL
);

CREATE TABLE chat_session_state (
  session_id VARCHAR(128) PRIMARY KEY,
  resume_id VARCHAR(64),
  last_slots_json TEXT,
  jobs_json TEXT,
  updated_at TIMESTAMPTZ,
  tool_events_json TEXT,
  resume_match_json TEXT,
  tenant_id VARCHAR(64) NOT NULL,
  user_id VARCHAR(64) NOT NULL
);

CREATE INDEX idx_agent_run_checkpoint_latest ON agent_run_checkpoint (session_id, created_at DESC, sequence DESC);
CREATE UNIQUE INDEX uk_agent_run_checkpoint_sequence ON agent_run_checkpoint (session_id, run_id, sequence);
CREATE INDEX idx_chat_message_owner_session ON chat_message_log (tenant_id, user_id, session_id, created_at);
CREATE INDEX idx_chat_message_session_created ON chat_message_log (session_id, created_at);
CREATE INDEX idx_chat_session_owner_updated ON chat_session_state (tenant_id, user_id, updated_at DESC);
CREATE INDEX idx_chat_session_updated ON chat_session_state (updated_at DESC);
