ALTER TABLE agent_run_checkpoint
  ADD COLUMN tenant_id VARCHAR(64),
  ADD COLUMN user_id VARCHAR(64);

CREATE INDEX idx_agent_run_checkpoint_owner_run
  ON agent_run_checkpoint (tenant_id, user_id, session_id, run_id, sequence DESC);

CREATE TABLE agent_run_resume_claim (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  session_id VARCHAR(128) NOT NULL,
  source_run_id VARCHAR(128) NOT NULL,
  resumed_run_id VARCHAR(128) NOT NULL,
  tenant_id VARCHAR(64) NOT NULL,
  user_id VARCHAR(64) NOT NULL,
  claimed_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uk_agent_run_resume_claim_source UNIQUE (session_id, source_run_id),
  CONSTRAINT uk_agent_run_resume_claim_target UNIQUE (resumed_run_id)
);

CREATE INDEX idx_agent_run_resume_claim_owner
  ON agent_run_resume_claim (tenant_id, user_id, session_id, claimed_at DESC);
